# Generated by Django 3.1.2 on 2020-10-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correoElectronico', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('cuidad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('codigoPostal', models.IntegerField()),
                ('numeroTelefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('idDetallePedido', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('descuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idPedidos', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaCompra', models.DateField()),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
