# Generated by Django 3.1.2 on 2020-10-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoria_cliente_detallepedido_pedidos_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
